import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="p-5 bg-gray-800 text-white">
          <nav className="flex justify-between">
            <a href="/" className="text-lg font-semibold">
              Home
            </a>
            <a href="/contact" className="text-lg font-semibold">
              Contact
            </a>
          </nav>
        </header>
        <main className="p-6">{children}</main>
        <footer className="p-5 bg-gray-800 text-white text-center">
          © 2024 My Portfolio
        </footer>
      </body>
    </html>
  );
}
