import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="p-5 bg-gray-800 text-white">
          <nav className="flex justify-between">
            <a href="/" className="text-lg font-semibold">
              Home
            </a>
            <a href="/contact" className="text-lg font-semibold">
              Contact
            </a>
          </nav>
        </header>
        <main className="p-6">{children}</main>
        <footer className="p-5 bg-gray-800 text-white text-center">
          © 2024 My Portfolio
        </footer>
      </body>
    </html>
  );
}
